/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';

var Teacher = require('../api/teacher/teacher.model');
var User = require('../api/user/user.model');

Teacher.find({}).remove(function () {
  var teachersLength = teachers.length;
  for (var i = 0; i < teachersLength; i++) {
    var teacher = teachers[i];

    Teacher.create(teacher);
  };
});

User.find({}).remove(function () {
  User.create({
    provider: 'local',
    name: 'Test 001',
    username: 'test001',
    password: 'test',
    branchId: 1,
    status: 1
  }, {
    provider: 'local',
    name: 'Test 002',
    username: 'test002',
    password: 'test',
    branchId: 2,
    status: 1
  }, {
    provider: 'local',
    role: 'admin',
    name: 'Admin',
    username: 'admin',
    password: 'admin',
    branchId: 1,
    status: 1
  }, function() {
      console.log('finished populating users');
    }
  );
});

var teachers = [
  {  
    "branchId":2,
    "id":1001,
    "firstname":"มณฑ์วรัชญ์",
    "lastname":"วรรณสุขนุกูล",
    "nickname":"กิ๊ฟ",
    "contacts": {
      "phones":[  
        {  
          "label":"เบอร์บ้าน",
          "value":"029628404",
          "isPrimary":false
        },
        {  
          "label":"เบอร์มือถือ",
          "value":"0819164373",
          "isPrimary":false
        }
      ],
      "emails":[  
        {  
          "label":"อีเมล์",
          "value":"monwarach@hotmail.com",
          "isPrimary":false
        }
      ]
    },
    "status":1
  },
  {  
    "branchId":1,
    "id":1002,
    "firstname":"ศิรภัสสร",
    "lastname":"สัพโส",
    "nickname":"อั๋น",
    "contacts": {
      "phones":[  
        {  
          "label":"เบอร์บ้าน",
          "value":"021010588",
          "isPrimary":false
        },
        {  
          "label":"เบอร์มือถือ",
          "value":"0818562100",
          "isPrimary":false
        }
      ],
      "emails":[  
        {  
          "label":"อีเมล์",
          "value":"info@pianoforte.com",
          "isPrimary":false
        }
      ]
    },
    "status":1
  },
  {  
    "branchId":1,
    "id":1003,
    "firstname":"รัตนวลี",
    "lastname":"โกศลธนศังกร",
    "nickname":"ลี่",
    "contacts": {
      "phones":[  
        {  
          "label":"เบอร์มือถือ",
          "value":"0890212111",
          "isPrimary":false
        }
      ],
      "emails":[  
        {  
          "label":"อีเมล์",
          "value":"iam_liing@hotmail.com",
          "isPrimary":false
        }
      ]
    },
    "status":1
  },
  {  
    "branchId":1,
    "id":1004,
    "firstname":"ดุจหทัย",
    "lastname":"นิยมสรวญ",
    "nickname":"ฟ่าย",
    "contacts": {
      "phones":[  
        {  
          "label":"เบอร์บ้าน",
          "value":"021010588",
          "isPrimary":false
        }
      ],
      "emails":[  
        {  
          "label":"อีเมล์",
          "value":"faifaiz89@gmail.com",
          "isPrimary":false
        }
      ]
    },
    "status":4
  },
  {  
    "branchId":1,
    "id":1005,
    "firstname":"วณิฐา",
    "lastname":"ช้างแก้ว",
    "nickname":"ส้ม",
    "phones":[  
      {  
        "label":"เบอร์มือถือ",
        "value":"0810000000",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"blossssw@gmail.com",
        "isPrimary":false
      }
    ],
    "status":4
  },
  {  
    "branchId":1,
    "id":1006,
    "firstname":"สกานท์",
    "lastname":"ศรีจันทร์สุข",
    "nickname":"กานท์",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"karn_wy@hotmail.com",
        "isPrimary":false
      }
    ],
    "status":4
  },
  {  
    "branchId":1,
    "id":1007,
    "firstname":"ถวิกา",
    "lastname":"ธารีสาร",
    "nickname":"เนย",
    "phones":[  

    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"i_am_nuei@hotmail.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1008,
    "firstname":"สุขวรรณ",
    "lastname":"ไพโรจน์วิทยาภรณ์",
    "nickname":"ลูกตาล",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"020000000",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"t_a_r_n_73@hotmail.com",
        "isPrimary":false
      }
    ],
    "status":4
  },
  {  
    "branchId":1,
    "id":1009,
    "firstname":"ศศิวิมล",
    "lastname":"เนตรพ่วง",
    "nickname":"แป้ง",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"pangrum_p@hotmail.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1010,
    "firstname":"สุนทรเทพ",
    "lastname":"อ่อนศิลา",
    "nickname":"จังคุง",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"jangcrub@gmail.com",
        "isPrimary":false
      }
    ],
    "status":4
  },
  {  
    "branchId":1,
    "id":1011,
    "firstname":"ณัฐวุฒิ",
    "lastname":"ใยมณี",
    "nickname":"โอม",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"020000000",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"yai.nuttawut@gmail.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1012,
    "firstname":"สิวารมย์",
    "lastname":"รังสิโยภาส",
    "nickname":"กวาง",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"siwarom@gmail.com",
        "isPrimary":false
      }
    ],
    "status":4
  },
  {  
    "branchId":1,
    "id":1013,
    "firstname":"กชพร",
    "lastname":"ศรีบารมี",
    "nickname":"ออม",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"a-aom24@live.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1014,
    "firstname":"เอกบุตรี",
    "lastname":"ศลโกสุม",
    "nickname":"เอก",
    "phones":[  

    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"ekbuttree@hotmail.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1015,
    "firstname":"รยานันท์",
    "lastname":"สิทธาทิพย์",
    "nickname":"เดียร์",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"ddeardog@gmail.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1016,
    "firstname":"นนท์",
    "lastname":"หิรัญวัฒน์ศิริ",
    "nickname":"นนท์",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010101",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"fanaticz1991@hotmail.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1017,
    "firstname":"ถวัลยรัตน์",
    "lastname":"ธารีสาร",
    "nickname":"แยม",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"yammyhip.zhu@yahoo.com",
        "isPrimary":false
      }
    ],
    "status":4
  },
  {  
    "branchId":1,
    "id":1018,
    "firstname":"เมธัสสา",
    "lastname":"ขันธุ์สุวรรณ",
    "nickname":"เกด",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"maytassak@yahoo.com",
        "isPrimary":false
      }
    ],
    "status":4
  },
  {  
    "branchId":1,
    "id":1019,
    "firstname":"ทิพย์วธู",
    "lastname":"อร่ามวิทยา",
    "nickname":"ปิ่น",
    "phones":[  
      {  
        "label":"เบอร์บ้าน",
        "value":"021010588",
        "isPrimary":false
      }
    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"pin_pianoforte@hotmail.com",
        "isPrimary":false
      }
    ],
    "status":1
  },
  {  
    "branchId":1,
    "id":1020,
    "firstname":"คณานันท์",
    "lastname":"ณ นคร",
    "nickname":"จอม",
    "phones":[  

    ],
    "emails":[  
      {  
        "label":"อีเมล์",
        "value":"kananant@yahoo.com",
        "isPrimary":false
      }
    ],
    "status":1
  }
];